"""
This type stub file was generated by pyright.
"""

import os
from typing import Self
from dataclasses import dataclass

"""
This type stub file was generated by pyright.
"""
@dataclass
class WinPath(str):
    path: str
    sep: str = ...
    pardir: str = ...
    altsep: str = ...
    extsep: str = ...
    def __post_init__(self) -> None:
        ...
    
    def __truediv__(self, other: Self | str) -> Self:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def exists(self) -> bool:
        ...
    
    def split_path(self: Self) -> tuple[Self, ...]:
        ...
    
    def split_drive(self: Self) -> tuple[Self, ...]:
        ...
    
    def split_ext(self: Self) -> tuple[Self, str, str]:
        ...
    
    def expand_user(self: Self) -> Self:
        ...
    
    def expand_vars(self: Self) -> Self:
        ...
    
    def norm_case(self: Self) -> Self:
        ...
    
    def basename(self: Self) -> Self:
        ...
    
    def dirname(self: Self) -> Self:
        ...
    
    def abspath(self: Self) -> Self:
        ...
    
    def realpath(self: Self) -> Self:
        ...
    
    def getsize(self: Self) -> int:
        ...
    
    def stat(self: Self) -> os.stat_result:
        ...
    
    def join_paths(self: Self, *paths: str) -> Self:
        ...
    
    def listdir(self: Self) -> list[Self]:
        ...
    
    def ls(self: Self) -> list[Self]:
        ...
    
    @property
    def parent(self: Self) -> Self:
        ...
    
    @property
    def ext(self: Self) -> str:
        ...
    
    @property
    def base(self: Self) -> Self:
        ...
    
    @property
    def is_dir(self) -> bool:
        ...
    
    @property
    def is_file(self) -> bool:
        ...
    
    @property
    def is_symlink(self) -> bool:
        ...
    
    @property
    def is_mount(self) -> bool:
        ...
    
    @property
    def is_absolute(self) -> bool:
        ...
    
    @property
    def is_relative(self) -> bool:
        ...
    


